### ISSUE TITLE
what is the music player name?

### ISSUE THREAD

**Issue by daUnknownCoder** [kotontrion/kompass#1]
is it some upgraded cava+mpv thing?
![image](https://github.com/user-attachments/assets/889a9b90-dbf1-403a-8697-cb3fdc4e9bb9)

**Comment by kotontrion** [comment]
The music player on the right is amberol.
The audio control center is [wire control](https://github.com/kotontrion/wirecontrol)
The bottom left are part of my quick settings popup and included in this rep.

**Comment by daUnknownCoder** [comment]
ohh, i didnt ask abt the audio control center coz i thought it was `pavucontrol`, now does this solve the playback issue? like i have a problem with wayland, where i dont have any audio and theres i cant play any video if its not on mute, i have to open `pavucontrol` (pulseaudio is backend) and go to configurations and switch between `Analog Stereo Output` and `Analog Stereo Duplex` and `Analog Stereo Input` (The default is `Analog Stereo Duplex`)

**Comment by kotontrion** [comment]
I don't think it will. This sounds like more of an issue with your pipewire/wireplumber configuration.

I initially wrote this to test the astal-wireplumber library and it evolved into its own thing. It does not have feature parity with pavucontrol. For example you cant switch profiles or change the routes yet.

**Comment by daUnknownCoder** [comment]
oh dem, so is there any way with which i can edit my pipewire config?


https://github.com/user-attachments/assets/39325147-9c1e-40f7-a36b-dbeb80bd59c7

this is happening...

**Comment by kotontrion** [comment]
that is weird.
I don't think I can help here, sorry.

I recommend gathering more information from the logs an ask in your distros support forum.

**Comment by daUnknownCoder** [comment]
like ik thats not your problem or something, but i was wondering what might be the reason because this is bugging me for quite a while, and i do use reddit and im on hyprland cathedral discord but idk how to describe what is happening
