### ISSUE TITLE
Can't Build project due to Cava

### ISSUE THREAD

**Issue by TrentJustTrent** [kotontrion/kompass#2]
Hello. I understand that these are your personal dots and aren't really looking to maintain it to a degree for others. I do have a quick question though. I'm on arch, installed astal-meta package for all the libraries, made sure I had all the dependencies for you bar and everything. However, when it comes to running meson install -C build I keep getting this error. I've also attempted to do everything from source and got the same issue. Do you mind lending a hand or pointing me in the right direction?

Much appreciated
![Screenshot 2024-11-17 172738](https://github.com/user-attachments/assets/c5734de5-2712-48fe-a9c1-ff523f4fbf59)

**Comment by kotontrion** [comment]
This projects makes use of the gtk4 version of the astal-tray lib, which has not been merged yet. 
Building kompass from a previous commit should work, so try building from https://github.com/kotontrion/kompass/commit/deff96521038a411d750abcf3fc02121b575f3ad
Or build the astal-tray lib from its gtk4 branch.

**Comment by TrentJustTrent** [comment]
Gotcha gotcha. Once again. Much appreciated!
